### ISSUE TITLE
Allow us to have some control under close and back buttons

### ISSUE THREAD

**Issue by NathanAP** [tomwyr/loader-search-bar#7]
Hello! I have some suggestions:

- Currently when you click to go back while having data in the search field we are sent to the last screen. This could be optional, so we would be able to make the 'back arrow' act as a 'clear' before go back.

- This one is the next step of the other: I believe we should see the defaultBar after we clear data too. Currently, if we click the Search bar (iconified or not), even clicking the clear icon twice we'll keep seeing the hint of the search bar. We should be able to see the default app bar again.

Sorry if I wasn't really clear in my suggestions and thanks for your effort with this package!

**Comment by tomwyr** [comment]
Hi, Nathan. Thanks for the suggestions you've come up with.
While I don't think this should be default behavior, to have *clear* and *back* buttons doing the same, I can see it as an optional thing.
I've added few commits to a new branch that allow to specify `SearchBarController` object in widget's constructor. Would you try using it and give some feedback then (specifically if it lets you react as in the use case you described)?

Here's pubspec dependency to the new branch:
```dart
loader_search_bar:
  git:
    url: git://github.com/tomwyr/loader-search-bar.git
    ref: search-bar-controller
```

**Comment by tomwyr** [comment]
I also created [an example](https://gist.github.com/tomwyr/0e053545296d0068d3e55396f955c1b5) that shows how it can be used to handle *clear/cancel* callbacks on your own.

**Comment by NathanAP** [comment]
Thanks for your effort! I'll test ASAP!

**Comment by NathanAP** [comment]
Hi @tomwyr !

I made some tests with the new features and it worked really well! I used both SearchBarController.isEmpty and SearchBarController.isFocused to make the close/clear work, but I didn't find a good way to make the defaultAppBar being show again. Am I losing something to do it? I notice SearchBarController.isActivate is always true after I click on the search (Iconified) and if I use something like
```
return new Scaffold(
  appBar: controller.isActivate ? new SearchBar() : new DefaultAppBar()
);
```

I get an error since the controller has no clients yet. Maybe I lost something in the logic?

**Comment by tomwyr** [comment]
You need to pass `DefaultAppBar` as SearchBar's `defaultBar` parameter, rather than creating both bars as separate widgets by yourself.
You should be able to bring back `DefaultAppBar` by simply calling `controller.cancelSearch` method after SearchBar's been activated (or tapping *back arrow* button, in case you didn't override it's behavior via `controller.onCancelSearch`).

Thank you for the feedback, @NathanAP ! Please let me know if it solves your issue.

**Comment by NathanAP** [comment]
Sorry for late reply, I tested this morning with this code:

```
searchController = new SearchBarController(
      onActivatedChanged: (active) {
        if (!active)
          Navigator.pop(context);
      },
      onCancelSearch: () {

        if (searchController.isEmpty && !searchController.isFocused) {
          Navigator.pop(context);
          return;
        }

        setState(() {
//       searchController.cancelSearch();
          searchController.clearQuery();
          lastQuery = '';
        });
      },
      onClearQuery: () {
        setState(() {
          searchController.clearQuery();
          lastQuery = '';
        });
      }
    );
```
if I uncomment the cancelSearch(), my back button go back one screen like it was doing before. Oh, and I'm using defaultAppBar in the SearchBar, I was just wondering what if I was doing the right way.

**Comment by tomwyr** [comment]
You should just call *cancelSearch* method in such case - it will bring *defaultAppBar* back in place of the search bar. This is because both search bar and default app bar are built within the same widget (which means no new page is pushed with `Navigator.push` method).

**Comment by NathanAP** [comment]
Hello! I've update my Flutter version to 0.11.12 (beta) and now I can't use your dependency anymore. I keep getting the error above while using SearchbarController, but I believe I need to review what I'm doing in my code to make it work as I need. If you're saying you could make it, maybe I need to think in a better logic to do it.

Here is the error: 

```
I/flutter (23421): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (23421): The following NoSuchMethodError was thrown building ProductList(dirty, state:
I/flutter (23421): _ProductListState#f6ef8):
I/flutter (23421): Class 'AutoActive' has no instance method 'call'.
I/flutter (23421): Receiver: Instance of 'AutoActive'
I/flutter (23421): Tried calling: call()
I/flutter (23421): 
I/flutter (23421): When the exception was thrown, this was the stack:
I/flutter (23421): #0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:50:5)
I/flutter (23421): #1      new SearchBar (package:loader_search_bar/src/SearchBar.dart:46:55)
I/flutter (23421): #2      _ProductListState.build (package:amo_delivery/window/establishment/product_list.dart:176:19)
I/flutter (23421): #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:3787:27)
I/flutter (23421): #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3699:15)
I/flutter (23421): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (23421): #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
I/flutter (23421): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3826:11)
I/flutter (23421): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
I/flutter (23421): #9      Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (23421): #10     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (23421): #11     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (23421): #12     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (23421): #13     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
I/flutter (23421): #14     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
I/flutter (23421): #15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (23421): #16     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (23421): #17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4838:14)
I/flutter (23421): #18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (23421): #19     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (23421): #20     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4838:14)
I/flutter (23421): #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (23421): #22     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (23421): #23     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4838:14)
I/flutter (23421): #24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (23421): #25     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (23421): #26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (23421): #27     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (23421): #28     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
I/flutter (23421): #29     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3826:11)
I/flutter (23421): #30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
I/flutter (23421): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (23421): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (23421): #33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (23421): #34     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (23421): #35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
I/flutter (23421): #36     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3826:11)
I/flutter (23421): #37     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
I/flutter (23421): #38     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (23421): #39     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (23421): #40     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4838:14)
I/flutter (23421): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (23421): #42     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (23421): #43     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (23421): #44     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (23421): #45     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
I/flutter (23421): #46     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
I/flutter (23421): #47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (23421): #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (23421): #49     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4838:14)
I/flutter (23421): #50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (23421): #51     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (23421): #52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (23421): #53     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (23421): #54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
I/flutter (23421): #55     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3826:11)
I/flutter (23421): #56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
I/flutter (23421): #57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (23421): #58     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (23421): #59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (23421): #60     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (23421): #61     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
I/flutter (23421): #62     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
I/flutter (23421): #63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (23421): #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (23421): #65     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:4838:14)
I/flutter (23421): #66     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (23421): #67     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (23421): #68     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (23421): #69     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (23421): #70     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
I/flutter (23421): #71     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
I/flutter (23421): #72     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (23421): #73     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (23421): #74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (23421): #75     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (23421): #76     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
I/flutter (23421): #77     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3826:11)
I/flutter (23421): #78     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
I/flutter (23421): #79     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (23421): #80     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (23421): #81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (23421): #82     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (23421): #83     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3679:5)
I/flutter (23421): #84     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:3826:11)
I/flutter (23421): #85     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3674:5)
I/flutter (23421): #86     Element.inflateWidget (package:flutter/src/widgets/framework.dart:2950:14)
I/flutter (23421): #87     Element.updateChild (package:flutter/src/widgets/framework.dart:2753:12)
I/flutter (23421): #88     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:4621:32)
I/flutter (23421): #89     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4953:17)
I/flutter (23421): #90     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (23421): #91     _TheatreElement.update (package:flutter/src/widgets/overlay.dart:507:16)
I/flutter (23421): #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (23421): #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (23421): #94     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (23421): #95     StatefulElement.update (package:flutter/src/widgets/framework.dart:3856:5)
I/flutter (23421): #96     Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (23421): #97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (23421): #98     Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (23421): #99     ProxyElement.update (package:flutter/src/widgets/framework.dart:3968:5)
I/flutter (23421): #100    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (23421): #101    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4845:14)
I/flutter (23421): #102    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (23421): #103    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (23421): #104    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (23421): #105    StatefulElement.update (package:flutter/src/widgets/framework.dart:3856:5)
I/flutter (23421): #106    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (23421): #107    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4845:14)
I/flutter (23421): #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (23421): #109    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:4845:14)
I/flutter (23421): #110    Element.updateChild (package:flutter/src/widgets/framework.dart:2742:15)
I/flutter (23421): #111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3710:16)
I/flutter (23421): #112    Element.rebuild (package:flutter/src/widgets/framework.dart:3547:5)
I/flutter (23421): #113    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2286:33)
I/flutter (23421): #114    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:676:20)
I/flutter (23421): #115    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:219:5)
I/flutter (23421): #116    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:990:15)
I/flutter (23421): #117    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:930:9)
I/flutter (23421): #118    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:842:5)
I/flutter (23421): #119    _invoke (dart:ui/hooks.dart:154:13)
I/flutter (23421): #120    _drawFrame (dart:ui/hooks.dart:143:3)
```

**Comment by tomwyr** [comment]
I pushed several commits to the branch yesterday. Could you try to update your dependencies with `flutter packages` `get` / `upgrade` and then check if this error still occurs?

**Comment by tomwyr** [comment]
Thanks for reporting that @NathanAP . There was an issue with creation of one of the default attributes. Please update your dependency - it should run fine from now on.

**Comment by NathanAP** [comment]
Thanks it is working now! I just realized what I was doing in my 'onActivatedChanged'... I need a better logic, as I said. Anyway, it is working as it should work, thank you so much for your effort!

**Comment by tomwyr** [comment]
Nice to hear that. I've merged changes into `master` branch. You can still reference it in pubspec, until pub package is updated:
```
loader_search_bar:
  git:
    url: git://github.com/tomwyr/loader-search-bar.git
```
